name: Build Tweak .deb

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos
        uses: theos/actions-setup-theos@v1

      - name: Build Package
        run: |
          make package THEOS_PACKAGE_SCHEME=roothide FINALPACKAGE=1

      - name: Upload .deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DynamicIsland-deb
          path: packages/*.deb
